name: 'Créer des ressources Azure'

on: 
  workflow_dispatch:
  
env:
  TF_VAR_GITHUB_TOKEN: "${{ secrets.TOKEN }}"
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  Terraform:
    name: "Run terraform" 
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: "[+] Checkout code"
      uses: actions/checkout@v2

    - name: "[+] Github Enterprise configuration"
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}":x-oauth-basic@github.com".insteadOf "https://github.com"

    - name: "[+] Install AZ Cli"
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: "[+] Setup Azure CLI"
      uses: azure/actions/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

   
    - name: "[+] Terraform Init"
      run: |
        terraform init

    - name: "[+] Terraform Validate"
      run: |
        terraform validate

    - name: "[+] Terraform Plan"
      id: plan
      run: |
        terraform plan -out=tfplan
      continue-on-error: true

    - name: "[+] Terraform Apply"
      if: success() && github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve